<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Fix2Engine.Graphics</RootNamespace>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Shaders\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Input\Input.csproj" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="../Core/Core.csproj" />
      <ProjectReference Include="../Backends/Raylib/Raylib.csproj" />
    </ItemGroup>
</Project>
